xone/main/urls.py
from django.urls import path 
from . import views

app_name = 'main'


urlpatterns = [
    path('', views.main_page, name = 'main_page' ),
    path('u/<str:short_url>', views.urlre, name = 'urlre' ),

] 

xone/user/urls.py
from django.urls import path 
from . import views
from user.views import SigninView

app_name = 'user'


urlpatterns = [
    
    path('account', views.account, name = 'account' ),
    path('logout', views.logoutuser, name = 'logout' ),
    path('registr', views.registr, name = 'registr' ),
    path('authorization',  SigninView.as_view(), name = 'authorization'),
]

xone/xone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('user.urls')),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

xone/main/models.py
from django.db import models

# Create your models here.

xone/user/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.
class OwnerUrls(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    long_url = models.CharField(max_length=200, null=True, blank=True)
    short_url = models.CharField(max_length=50, null=True, blank=True)
    

    def __str__(self):
        return str(self.long_url)

    def get_absolute_url(self):
        return f'/url/{self.short_url}'

xone/user/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from .models import OwnerUrls
from django import forms



class UserRegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):   # игнорирование стандартных стилей 
        super().__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs.update({ 'class': 'form-control', 'placeholder': 'пароль' , 'rows': 1, })
        self.fields['password2'].widget.attrs.update({ 'class': 'form-control', 'placeholder': 'подтвердите пароль' , 'rows': 1, })
       
        self.fields['username'].widget.attrs.update({ 'class': 'form-control', 'placeholder': 'логин' , 'rows': 1, })
        

    class Meta:
        model = User
        fields = [ 'username', 'password1', 'password2']

    
class OwnerUrlsForm(ModelForm):
    def __init__(self, *args, **kwargs):   # игнорирование стандартных стилей 
        super().__init__(*args, **kwargs)
        self.fields['long_url'].widget.attrs.update({ 'class': 'form-control', 'placeholder': 'введите url' })
        
    
    class Meta:
        model = OwnerUrls
        fields = '__all__'
        exclude = ['owner', 'short_url',]
    
        

xone/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from user.forms import OwnerUrlsForm
from user.models import OwnerUrls
from django.contrib.auth import get_user_model
import short_url
import os
# Create your views here.
import qrcode
from django.http import HttpResponse

def main_page(request):
    user = request.user
    actual_key, actual_value, ownerlist = '', '', {}

    history = OwnerUrls.objects.all()
    form = OwnerUrlsForm()
    #print(request.user.is_authenticated)
    #print(user)
    waytoimg = '/'.join(os.path.abspath('img').split('\\'))
    
    if request.method == 'POST':
        form = OwnerUrlsForm(request.POST)
        if form.is_valid():
            surl = form.save(commit=False)
            surl.owner = user 
            surl.save()
            surl.short_url = short_url.encode_url(surl.id)
            
            img = qrcode.make(surl.short_url)
            type(img)  # qrcode.image.pil.PilImage
            img.save("img/testqr.jpg" )
            print('/'.join(os.path.abspath('img').split('\\')))
            surl.save()
            
            
            messages.success(request, 'Ссылка готова !')
            return redirect('main:main_page')

    for i in history:
        if i.owner == user:
                ownerlist[i.short_url] = i.long_url
                actual_key = list(ownerlist.keys())[-1::][0]
                actual_value = list(ownerlist.values())[-1::][0]
    return render(request, 'home/home.html', {'form': form, 'actual_key':actual_key, 'actual_value':actual_value, 'waytoimg':waytoimg, 'history':history })



def urlre(request, short_url):
    #elem = get_object_or_404(OwnerUrls, id=id)
    url = ''
    elem = OwnerUrls.objects.all()
    print(elem)
    for i in elem:
        print(i)
        if i.short_url == short_url: 
            url = i.long_url
    

            
    #return HttpResponse('hi!!!'+str(short_url ) )
    return redirect('{}'.format(url))

xone/user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages
from .forms import UserRegistrationForm
from django.contrib.auth import  logout
from django.views.generic import TemplateView
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
# Create your views here.
from .forms import OwnerUrlsForm
from .models import OwnerUrls
import time
def account(request ):
    ownerlist = {}
    actual = ''
    user = request.user
    history = OwnerUrls.objects.all()
    #--------------------------------------------->перевести в клас и передать во вьюс главный
    for i in history:
        if i.owner == user:
                ownerlist[i.short_url] = i.long_url
                actual = list(ownerlist.keys())[-1::][0]

    return render (request, 'user_pages/account-profile.html', {'user':user, 'ownerlist':ownerlist, 'history':history})



def registr(request):

    form = UserRegistrationForm(request.POST)
    data = {}
    if request.method == 'POST':
        if form.is_valid():
            form.save(commit='FALSE')
            form.changed_data
            
            messages.success(request, 'Отлично, теперь авторизируйтесь !')
            return redirect('user:authorization')
    else: 
        return render(request, 'user_pages/account-signin.html',{ 'form':form } ,)
    return render(request, 'user_pages/account-signin.html',{ 'form':form })


class SigninView(TemplateView):
    
    template_name = 'user_pages/account-login.html'

    def dispatch(self, request, *args, **kwargs):
        error_dict = {}
        
        if request.method == 'POST':
            
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                
                login(request, user)
                return redirect('user:account')
            else:
                 messages.success(request, 'Username/Password Invalid')

	    
        return render(request, self.template_name, error_dict)


def logoutuser(request):
    logout(request)
    return redirect('/')

xone/main/templates/home/home.html
{% extends 'index.html' %}

{% load static %}

{% block content %}
<div class="container mt-5"  >
    <div class="row">
        {% if messages %}
        <div class="alert alert-success">
            {% for message in messages %}
                <li class="{{ message.tags }}">
                    {{ message|safe }}
                    <a href="{% url 'main:main_page' %}" class="close">✖</a>
                </li>
            {% endfor %}
       </div>
    {% endif %}

    


        <h1>Привет {{user.username}}</h1>
        <hr>
          {% if request.user.is_authenticated %}
        <div class="col-6">
            <h4>Cокращение ссылок </h4>
           <div class = 'mx-auto'>
                <form  method="POST" action="">
                    {% csrf_token %}
                    {% for elem in form %}
                    {{elem}}
                    {% endfor %}
                    
                    <button type="submit" class="btn btn-primary mb-3 mt-2">Сократить</button> 

                </form>
                <table class="table table-sm ">
                    <thead>
                <tr class="table-success">
                    <tb>Ваша ссылка:</tb>
                 <th>
                    {% if actual_value %}
                    <a class="dropdown nav-item" href="{{actual_value}}" target="_blank">http://mytestdom.site/u/{{actual_key}}</a>
                    {% else %}
                    {% endif %}
                 </th>
                </thead>
                </tr>
            </table>
            </div>
        </div>
        
        <div class="col-4">
           {% if actual_value %}
            <img  src="img/testqr.jpg"  width="150" height = '150'>
            {% else %}
            {% endif %}
        </div>
        
        
        {% else %}
        <h3> Надо зайти или зарегистрироваться  :) </h3>
        {% endif %}
        </div>
        
        <div class="col-2">
        </div>
    </div>
</div>         
{% comment %} {% for i in history %}

<p><button><a href="{% url 'main:urlre' i.short_url %}">{{ i.short_url}}</a></button></p>
{% endfor %} {% endcomment %}
{% endblock content %}

xone/main/templates/index.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Иксван</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'main:main_page' %}">Иксван</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'main:main_page' %}">Главная</a>
              </li>
              {% if request.user.is_authenticated %}
              <li class="nav-item" ><a  class="nav-link active" aria-current="page" href="{% url 'user:account' %}"> История поиска </a></li>
            </ul>
              
              <div class="d-flex" >
                <div class="collapse navbar-collapse" >
              <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                
                <li class="nav-item" ><a  class="nav-link active" aria-current="page" href="{% url 'user:logout' %}"> Выход </a></li>
                 </ul>
                </div>
            </div>
                    {% else %}
                    
            </ul>
                    <div class="d-flex" >
                        <div class="collapse navbar-collapse" >
                            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                              <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'user:registr' %}">Регистрация</a>
                              </li>
                              <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'user:authorization' %}">Вход</a>
                              </li>
                            </ul>
                        </div>
                    </div>
                    {% endif %}
                    </div>
                    
            </div>
          
      </nav>


    {% block content %}
    {% endblock content %}


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
  </body>
</html>

xone/main/templates/urlform/urlform.html
{% extends 'index.html' %}
{% load static %}


{% block content %}


{{mestr}}
{% endblock content %}

xone/main/templates/user_pages/account-login.html
{% extends 'index.html' %}

{% load static %}

    {% block content %}

    {{ message }}
    
    <!-- Off-Canvas Wrapper-->
    {% comment %} <div class="offcanvas-wrapper">
        <!-- Page Title-->
        <div class="page-title">
          <div class="container">
            <div class="column">
              <h1> Вход</h1>
              {{error}}
            </div>
           
          </div>
        </div>
        <!-- Page Content-->
        <div class="container padding-bottom-3x mb-2">
          <div class="row">
            
        </div>

        <div class="col-md-6">

          <form class="login-box" method="POST">
              {% csrf_token %}
            <h4 class="margin-bottom-1x">Login in form below</h4>
            <div class="form-group input-group">


                <input class="form-control" type="text" name = 'username', placeholder="username"><span class="input-group-addon"><i class="icon-mail"></i></span>


            </div>
            <div class="form-group input-group">

                <input class="form-control" type="password" name = 'password', placeholder="password"><span class="input-group-addon"><i class="icon-lock"></i></span>

            </div>
            
            <div class="text-center text-sm-right">
                <input class="btn btn-primary margin-bottom-none" type="submit" value="login">
            </div>
          </form>

          
         


        </div>
           
          </div>
        </div>
        <!-- Site Footer-->
      
      </div>
 {% endcomment %}

 <div class="container">
    <div class="row">

        {% if messages %}
        <div class="alert alert-success">
            {% for message in messages %}
                <li class="{{ message.tags }}">
                    {{ message|safe }}
                    <a href="{% url 'user:authorization' %}" class="close">✖</a>
                </li>
            {% endfor %}
       </div>
    {% endif %}

        <div class="col-2">
           
            

          </div>
        <div class="col-4">
            <h3 class="margin-bottom-1x">Вход</h3>
      <form method="POST">
        <div class="mb-3">
            {% csrf_token %}
          <label for="exampleInputEmail1" class="form-label">Логин</label>
          <input class="form-control" type="text" name = 'username', placeholder="логин"><span class="input-group-addon"><i class="icon-mail"></i></span>
         
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Пароль</label>
          <input class="form-control" type="password" name = 'password', placeholder="пароль"><span class="input-group-addon"><i class="icon-lock"></i></span>
        </div>
       
        <button type="submit" class="btn btn-primary">Вход</button>
      </form>
    </div>
    <div class="col-6">
       
      </div>
      
    </div>
</div>




    {% endblock content %}

xone/main/templates/user_pages/account-profile.html
{% extends 'index.html' %}
{% load static %}

    {% block content %}
<div class="container mt-5"  >
    <div class="row">
        <h1>Итория сокращений {{user.username}}</h1>
        <hr>
        <table class="table table-bordered">
            <thead class="thead-dark" >
            <tr>
                <th class="col-sm-4">Укороченная ссылкка</th>
                <th class="col-6">Полная ссылка</th>
                
            </tr>
            </thead>
            {% for short,long in ownerlist.items %}
            
            <tbody>
               
            <tr> 
                
                <th ><a class="dropdown nav-item" href="{% url 'main:urlre' short %}" target="_blank">http://u/mytestdom.site/{{short}} </a></th>
                <td scope="row"><a class="dropdown nav-item" href="{{long}}" target="_blank">{{long}}</a></td>
                
                
            </tr>
            </tbody>
            {% empty %}
            <tr>
                
                <td colspan="2">Тут пока пусто...</td>
            </tr>
            {% endfor %}
        </table>
            </div>
        </div>
        
        <div class="col-4">
        </div>
        
        </div>
        <div class="col-2">
        </div>
    </div>
</div> 

{% endblock content %}

xone/main/templates/user_pages/account-signin.html
{% extends 'index.html' %}

{% load static %}

    {% block content %}

<div class="container">
    <div class="row">
        <div class="col-2">
           
          </div>
        <div class="col-4">

            
       
                      <h3 class="margin-bottom-1x">Регистрация</h3>
                      
                      <form class="row" method="POST">
                          {% csrf_token %}                      
                          <div class="mb-3">
                            <label for="reg-fn">Логин</label>
                            {{ form.username }}  
                        </div>
                          <div class="mb-3">
                            <label for="reg-pass">Пароль</label>
                            {% comment %} <input class="form-control" type="password" id="reg-pass" required> {% endcomment %}
                            {{ form.password1 }}  
                        </div>
                          <div class="mb-3">
                            <label for="reg-pass-confirm">Подтвердите пароль</label>
                            {% comment %} <input class="form-control" type="password" id="reg-pass-confirm" required> {% endcomment %}
                            {{ form.password2 }}
                        </div>
                        <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
                      </form>
          
                  
                 
               
    </div>
    <div class="col-6">
    </div>
      
    </div>
</div>
{% endblock content %}